# Generated by Django 4.2.19 on 2025-02-13 14:40

import apps.common.fields
import apps.common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redirect_url', models.URLField()),
                ('is_private', models.BooleanField(default=False)),
                ('redirect_identifier', apps.common.fields.IDField(_size=21, default=functools.partial(apps.common.utils.generate_id_with_prefix, *(), **{'_size': 21, 'prefix': 'redirect'}), max_length=30, prefix='redirect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
